project_id = "xftrrfomvmvllnwjroxp"

[functions.instagram-api]
verify_jwt = true

[functions.get-instagram-token]
verify_jwt = true

[functions.facebook-oauth]
verify_jwt = true

[functions.instagram-fetch-insights]
verify_jwt = true

[functions.facebook-instagram-insights]
verify_jwt = true

[functions.export-insights]
verify_jwt = true
